CREATE OR ALTER PROCEDURE GET_PERSON_DATA
RETURNS (
    ID_VAR INTEGER,
    NAME_VAR VARCHAR(100))
AS
BEGIN
BEGIN
  FOR SELECT ID, NAME FROM PERSON INTO :ID_VAR, :NAME_VAR DO
  BEGIN
    SUSPEND;
  END
END
END;
